name: Build Check

on: [push, pull_request]

jobs:
  build:
    name: Check Compilation
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Compile
      run: go build main.go
